name: Data Workflow

on:
  push:
    paths:
      - 'data/**'
  pull_request:
    paths:
      - 'data/**'

jobs:
  data_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache uv packages
        uses: actions/cache@v3
        with:
          path: ~/.uv
          key: ${{ runner.os }}-uv-${{ hashFiles('**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-

      - name: Install dependencies
        run: |
          python -m pip install uv
          uv sync

      - name: Run Statistics
        run: |
          uv run src/example_mlops/data.py > data_statistics.md
          echo '![](./mnist_images.png "MNIST images")' >> data_statistics.md
          echo '![](./train_label_distribution.png "Train label distribution")' >> data_statistics.md
          echo '![](./test_label_distribution.png "Test label distribution")' >> data_statistics.md

      - name: Setup cml
        uses: iterative/setup-cml@v2

      - name: Comment on PR
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cml comment create data_statistics.md --watermark-title="Data Checker"
