wandb_version: 1

lr:
  desc: null
  value: 1.046699673875214
epochs:
  desc: null
  value: 5
batch_size:
  desc: null
  value: 32
_wandb:
  desc: null
  value:
    python_version: 3.12.3
    cli_version: 0.19.2
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1736428417
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      3:
      - 14
      - 16
      - 23
      - 37
      4: 3.12.3
      5: 0.19.2
      8:
      - 5
      13: linux-x86_64
learning_rate:
  desc: null
  value: 1.046699673875214
